    在学TF2之前，请忘记静态图！请忘记静态图！请忘记静态图！

创建一个tensor

tf2.0中可以直接看到numpy的值

In [1]:
import tensorflow as tf
print(tf.__version__)

2.0.0-alpha0


In [2]:
tf.constant(1)

<tf.Tensor: id=0, shape=(), dtype=int32, numpy=1>

In [3]:
tf.constant(2, dtype=tf.float64)

<tf.Tensor: id=2, shape=(), dtype=float64, numpy=2.0>

In [4]:
tf.constant('hello world.')

<tf.Tensor: id=4, shape=(), dtype=string, numpy=b'hello world.'>

tensor放在cpu还是gpu?
默认放在cpu上

In [5]:
a = tf.constant(1)
a.device

'/job:localhost/replica:0/task:0/device:CPU:0'

In [6]:
with tf.device('cpu'):
    a = tf.constant([1])
a
a.device

'/job:localhost/replica:0/task:0/device:CPU:0'

In [7]:
with tf.device('gpu'):
    a = tf.range(4)
a

<tf.Tensor: id=11, shape=(4,), dtype=int32, numpy=array([0, 1, 2, 3])>

cpu gpu 互转

In [8]:
a = a.gpu()
a.device

'/job:localhost/replica:0/task:0/device:GPU:0'

In [9]:
a = a.cpu()
a.device

'/job:localhost/replica:0/task:0/device:CPU:0'

tensor转numpy

In [10]:
a = tf.range(3)
a

<tf.Tensor: id=18, shape=(3,), dtype=int32, numpy=array([0, 1, 2])>

In [11]:
a_numpy = a.numpy()
a_numpy

array([0, 1, 2])

In [12]:
a_numpy = int(a[0])
type(a_numpy)

int

检查tensor的类型

In [13]:
import numpy as np
a = tf.constant([1.])
b = tf.constant([True, False])
c = tf.constant('hello world')
d = np.arange(4)

In [14]:
isinstance(a, tf.Tensor)

True

In [15]:
tf.is_tensor(a) # 推荐使用，原因tf.Variable()是tensor,但是isinstance 无法识别

True

In [16]:
e = tf.Variable(1)
e

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1>

In [17]:
isinstance(e, tf.Tensor)

False

In [18]:
isinstance(e, tf.Variable)

True

In [19]:
tf.is_tensor(e)

True

In [20]:
a.dtype, b.dtype, c.dtype

(tf.float32, tf.bool, tf.string)

In [21]:
a.dtype == tf.float32

True

In [22]:
c.dtype == tf.string

True

numpy 转tensor

In [23]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [24]:
a.dtype

dtype('int32')

In [25]:
aa = tf.convert_to_tensor(a)
aa

<tf.Tensor: id=39, shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4])>

In [26]:
aa =tf.convert_to_tensor(a, dtype=tf.float32)
aa

<tf.Tensor: id=41, shape=(5,), dtype=float32, numpy=array([0., 1., 2., 3., 4.], dtype=float32)>

tensor 类型转换

In [27]:
aaa = tf.cast(aa, dtype=tf.double)
aaa

<tf.Tensor: id=43, shape=(5,), dtype=float64, numpy=array([0., 1., 2., 3., 4.])>

In [28]:
# 注意dtype是float64
tf.convert_to_tensor(np.ones([2, 3]))

<tf.Tensor: id=45, shape=(2, 3), dtype=float64, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]])>

bool and int

In [29]:
b = tf.constant([0, 1])
b

<tf.Tensor: id=47, shape=(2,), dtype=int32, numpy=array([0, 1])>

In [30]:
tf.cast(b, dtype=tf.bool)

<tf.Tensor: id=49, shape=(2,), dtype=bool, numpy=array([False,  True])>

tf.zeros

In [31]:
a = tf.zeros([2,3])
a


<tf.Tensor: id=53, shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [32]:
tf.zeros_like(a)

<tf.Tensor: id=55, shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

tf.ones

In [33]:
tf.ones(1) # 这里的1 == [1]

<tf.Tensor: id=59, shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>

In [34]:
tf.ones([]) # 传scalar

<tf.Tensor: id=61, shape=(), dtype=float32, numpy=1.0>

In [35]:
# vector
tf.ones([1])

<tf.Tensor: id=65, shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>

tf.fill

tensor填充想要的数

In [37]:
tf.fill([2, 2], 9)

<tf.Tensor: id=76, shape=(2, 2), dtype=int32, numpy=
array([[9, 9],
       [9, 9]])>

tf.random

In [38]:
tf.random.normal([2, 2], mean=1, stddev=1)

<tf.Tensor: id=83, shape=(2, 2), dtype=float32, numpy=
array([[ 1.4151616 ,  0.75409603],
       [-0.08040679,  0.6522907 ]], dtype=float32)>

In [39]:
tf.random.truncated_normal([2, 2], mean=0, stddev=1)

<tf.Tensor: id=90, shape=(2, 2), dtype=float32, numpy=
array([[ 0.33107063, -0.3921877 ],
       [ 0.45560092, -0.41723162]], dtype=float32)>

In [40]:
tf.random.uniform([2, 2], minval=0, maxval=1)

<tf.Tensor: id=98, shape=(2, 2), dtype=float32, numpy=
array([[0.04644084, 0.5306817 ],
       [0.1573863 , 0.7957505 ]], dtype=float32)>

tf.gather(a, idx)
根据idx收集a中的一些数


In [41]:
idx = tf.range(4)
idx = tf.random.shuffle(idx)
print('idx: ',idx)
a = tf.random.uniform([4], maxval=10, dtype=tf.int32)
print('a: ', a)
aa = tf.gather(a, idx)
aa

idx:  tf.Tensor([3 1 0 2], shape=(4,), dtype=int32)
a:  tf.Tensor([3 7 9 4], shape=(4,), dtype=int32)


<tf.Tensor: id=112, shape=(4,), dtype=int32, numpy=array([4, 7, 3, 9])>

loss

In [42]:
# 网络输出out [b, 10] = [4, 10]
out = tf.random.uniform([4, 10])
out

<tf.Tensor: id=120, shape=(4, 10), dtype=float32, numpy=
array([[0.8271313 , 0.29440045, 0.9604119 , 0.33669078, 0.92162895,
        0.32094002, 0.6888763 , 0.19028652, 0.1488576 , 0.01857793],
       [0.34474874, 0.69677114, 0.94943976, 0.7805033 , 0.6940813 ,
        0.10317683, 0.44957805, 0.5571593 , 0.32398295, 0.40015626],
       [0.4643277 , 0.54785156, 0.39093208, 0.20444894, 0.52085173,
        0.09884453, 0.5896226 , 0.4442371 , 0.03139639, 0.40095294],
       [0.60203075, 0.48884344, 0.15060663, 0.04446554, 0.7103659 ,
        0.62882423, 0.65154386, 0.9018471 , 0.26229584, 0.7680534 ]],
      dtype=float32)>

In [43]:
# label y [b] => [b, 10]
y = tf.range(4)
y = tf.one_hot(y, depth=10)
print(y.shape)
y

(4, 10)


<tf.Tensor: id=129, shape=(4, 10), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [45]:
loss = tf.keras.losses.mse(y, out)
loss = tf.reduce_mean(loss)
loss

<tf.Tensor: id=141, shape=(), dtype=float32, numpy=0.2969864>

Vector and Matrix
(bias and weights)

In [46]:
from tensorflow.keras import layers


In [47]:
net = layers.Dense(10)
net.build((4, 8))
net.kernel

<tf.Variable 'kernel:0' shape=(8, 10) dtype=float32, numpy=
array([[-0.4858433 ,  0.31981456,  0.13905162, -0.2508697 ,  0.48718548,
         0.3147136 , -0.020688  ,  0.23889047, -0.31776863, -0.38435072],
       [-0.44753584,  0.09830803, -0.3874122 ,  0.19779956, -0.28057835,
        -0.1305975 , -0.3743531 , -0.5388241 ,  0.11132097, -0.40891936],
       [-0.4636055 ,  0.5348172 , -0.01116514,  0.20384616,  0.509169  ,
         0.12296736, -0.5292312 ,  0.22822553,  0.5637996 , -0.5340536 ],
       [ 0.13152999, -0.3856101 , -0.20238584,  0.48257804,  0.5605731 ,
         0.23294973,  0.3466277 , -0.34514165, -0.25734755,  0.15559578],
       [-0.17090848,  0.04876798,  0.11940539, -0.317419  ,  0.33635497,
         0.11153162, -0.11954924,  0.1721034 , -0.115978  , -0.2535225 ],
       [-0.05159879,  0.3211978 , -0.38127628,  0.5421041 , -0.4980085 ,
         0.29808962, -0.40836215, -0.05448616, -0.24131617, -0.10691038],
       [ 0.543561  ,  0.1847862 ,  0.1657576 ,  0.02631366

In [48]:
net.bias

<tf.Variable 'bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>

索引和切片

In [49]:
a = tf.ones([1,5,5,3])
# python 风格的索引
a[0][0]

<tf.Tensor: id=181, shape=(5, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [50]:
# numpy 风格的索引
a[0, 0]

<tf.Tensor: id=186, shape=(5, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

start:end

In [51]:
a = tf.range(10)
a

<tf.Tensor: id=191, shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [53]:
a[1:3]

<tf.Tensor: id=201, shape=(2,), dtype=int32, numpy=array([1, 2])>

In [52]:
# -1是最右边的索引  
a[-1:]

<tf.Tensor: id=196, shape=(1,), dtype=int32, numpy=array([9])>

In [54]:
a[-2:]

<tf.Tensor: id=206, shape=(2,), dtype=int32, numpy=array([8, 9])>

In [55]:
# 除了最后一个都取
a[:-1]

<tf.Tensor: id=211, shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8])>

In [56]:
a = tf.ones([4, 28, 28, 3])
a.shape


TensorShape([4, 28, 28, 3])

In [57]:
a[:, :, :, 0].shape

TensorShape([4, 28, 28])

In [58]:
a[:, 0, :, 0].shape

TensorShape([4, 28])

start:end:step

::step

In [59]:
a = tf.range(10)
a.shape

TensorShape([10])

In [60]:
# step=2
a[1:8:2]

<tf.Tensor: id=231, shape=(4,), dtype=int32, numpy=array([1, 3, 5, 7])>

In [61]:
a[::2]

<tf.Tensor: id=236, shape=(5,), dtype=int32, numpy=array([0, 2, 4, 6, 8])>

::-1 翻转tensor

In [62]:
a[::-1]

<tf.Tensor: id=241, shape=(10,), dtype=int32, numpy=array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])>

...

In [63]:
a = tf.random.normal([2, 4, 28, 28, 3])
a[0].shape

TensorShape([4, 28, 28, 3])

In [64]:
a[0, :, :, :, :].shape

TensorShape([4, 28, 28, 3])

In [65]:
a[0, ...].shape

TensorShape([4, 28, 28, 3])

tf.gather  对一个维度获取值

data: [classes, students, subjects]

In [66]:
a = tf.ones([4, 35, 8])
a.shape

TensorShape([4, 35, 8])

In [67]:
# 获取某两个班级的所有学生的所有成绩
tf.gather(a, axis=0, indices=[0, 1]).shape

TensorShape([2, 35, 8])

tf.gather_nd 对多个维度获取值

In [68]:
tf.gather_nd(a, [0]).shape

TensorShape([35, 8])

In [69]:
tf.gather_nd(a, [0, 1, 2]).shape

TensorShape([])

In [71]:
# 取[0, 0，:] 和 [1, 1, :]
# shape [1,1,8] + [1,1,8] => [2, 8]
tf.gather_nd(a, [[0, 0], [1, 1]]).shape

<tf.Tensor: id=274, shape=(2, 8), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [76]:
b = tf.random.uniform([4, 4, 1], maxval=10, minval=0, dtype=tf.int32)
b

<tf.Tensor: id=300, shape=(4, 4, 1), dtype=int32, numpy=
array([[[5],
        [6],
        [2],
        [4]],

       [[8],
        [0],
        [3],
        [4]],

       [[3],
        [5],
        [5],
        [7]],

       [[7],
        [9],
        [4],
        [3]]])>

In [79]:
tf.gather_nd(b, [[0, 0], [3, 2]])

<tf.Tensor: id=309, shape=(2, 1), dtype=int32, numpy=
array([[5],
       [4]])>

In [68]:
# [1,1,1] + [1,1,1] + [1,1,1] =>[3]
tf.gather_nd(a, [[0, 0, 0], [1,1,1],[3,3,3]])

<tf.Tensor: id=255, shape=(3,), dtype=float32, numpy=array([1., 1., 1.], dtype=float32)>

tf.boolean_mask

In [69]:
a.shape

TensorShape([4, 35, 8])

In [70]:
# 保留mask矩阵中True部分
tf.boolean_mask(a, mask=[True, True, False, False], axis=0).shape

TensorShape([2, 35, 8])

In [71]:
a = tf.ones([2,3])
tf.boolean_mask(a, mask=[True, True])


<tf.Tensor: id=315, shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [74]:
a = tf.random.normal([4, 28, 28, 3])
a.shape


TensorShape([4, 28, 28, 3])

tf.reshape

In [78]:
tf.reshape(tf.reshape(a, [4, -1]), [4, 28, 28, 3]).shape

TensorShape([4, 28, 28, 3])

tf.transpose

In [81]:
a = tf.random.normal((4, 3, 2, 1))
a.shape

TensorShape([4, 3, 2, 1])

In [82]:
# 默认将维度倒置
tf.transpose(a).shape

TensorShape([1, 2, 3, 4])

In [83]:
# [4, 3, 2, 1] => [4, 3, 1, 2]
tf.transpose(a, perm=[0, 1, 3, 2]).shape

TensorShape([4, 3, 1, 2])

squeeae vs expand_dims

In [85]:
a = tf.random.normal([4, 35, 8])
a.shape

TensorShape([4, 35, 8])

In [86]:
tf.expand_dims(a, axis=0).shape

TensorShape([1, 4, 35, 8])

In [111]:
tf.expand_dims(a, axis=-1).shape

TensorShape([4, 1])

In [113]:
tf.squeeze(tf.zeros([1,2,1,1,3])).shape

TensorShape([2, 3])

In [115]:
a = tf.zeros([1,2,1,3])

In [116]:
tf.squeeze(a).shape

TensorShape([2, 3])

In [118]:
b = tf.random.normal([1,4,35,8])
tf.squeeze(b).shape

TensorShape([4, 35, 8])

In [120]:
tf.squeeze(b, axis=0).shape

TensorShape([4, 35, 8])

In [124]:

tf.squeeze(b, axis=-4).shape

TensorShape([4, 35, 8])

broadcasting

1、右对齐

2、维度不一致，补齐（补1）

3、将维度为1的那些轴扩充成两者中较长的维度

ps:广播机制实现维度扩充并不会存储在内存或显存中，只是对计算的一个优化

In [126]:
x = tf.random.normal([4,32,32, 3])
y = tf.random.normal([3])
z = x + y
z.shape


TensorShape([4, 32, 32, 3])

In [129]:
# broadcast_to 原地更新（inplace）
x = tf.broadcast_to(y, x.shape)
x.shape

TensorShape([4, 32, 32, 3])

broadcast vs tile

In [137]:
a = tf.ones([3, 4])
a1 = tf.broadcast_to(a, [2, 3, 4])
a1


<tf.Tensor: id=550, shape=(2, 3, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

In [138]:
# 用tf.expand_dims 和tf.tile实现tf.broadcast功能
# 区别： tf.tile会把扩展的值保存在内存中
a2 = tf.expand_dims(a, axis=0)
a2.shape

TensorShape([1, 3, 4])

In [139]:
a3 = tf.tile(a2, [2, 1, 1])
a3

<tf.Tensor: id=555, shape=(2, 3, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

数学运算

element-wise:  +-*/

matrix-wise:   @  matmul

dim-wise:    reduce_mean/max/min/sum

In [143]:
a = tf.fill([2, 2], 2)
b = tf.ones([2,2], dtype=tf.int32)
print(a+b)
print(a-b)
print(a*b)
print(a/b)

tf.Tensor(
[[3 3]
 [3 3]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1 1]
 [1 1]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[2 2]
 [2 2]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[2. 2.]
 [2. 2.]], shape=(2, 2), dtype=float64)


In [144]:
# 地板除
b//a

<tf.Tensor: id=586, shape=(2, 2), dtype=int32, numpy=
array([[0, 0],
       [0, 0]])>

tf.math.log

tf.exp


In [153]:
a


<tf.Tensor: id=572, shape=(2, 2), dtype=int32, numpy=
array([[2, 2],
       [2, 2]])>

In [155]:
a = tf.cast(a, dtype=tf.float32)
tf.exp(a)


<tf.Tensor: id=594, shape=(2, 2), dtype=float32, numpy=
array([[7.389056, 7.389056],
       [7.389056, 7.389056]], dtype=float32)>

In [156]:
tf.math.log(a)

<tf.Tensor: id=596, shape=(2, 2), dtype=float32, numpy=
array([[0.6931472, 0.6931472],
       [0.6931472, 0.6931472]], dtype=float32)>

In [160]:
# log 以e为底数
tf.math.log(10.)

<tf.Tensor: id=606, shape=(), dtype=float32, numpy=2.3025851>

In [162]:
# log2(8)实现:换底公式
log_2 = tf.math.log(8.) / tf.math.log(2.)
log_2

<tf.Tensor: id=617, shape=(), dtype=float32, numpy=3.0>

In [163]:
# log10(10)实现：
log_10 = tf.math.log(100.) / tf.math.log(10.)
log_10

<tf.Tensor: id=623, shape=(), dtype=float32, numpy=2.0>

pow 

sqrt

In [165]:
b = tf.fill([2,2], 2.)
b

<tf.Tensor: id=631, shape=(2, 2), dtype=float32, numpy=
array([[2., 2.],
       [2., 2.]], dtype=float32)>

In [166]:
tf.pow(b, 3)

<tf.Tensor: id=634, shape=(2, 2), dtype=float32, numpy=
array([[8., 8.],
       [8., 8.]], dtype=float32)>

In [167]:
b**3

<tf.Tensor: id=637, shape=(2, 2), dtype=float32, numpy=
array([[8., 8.],
       [8., 8.]], dtype=float32)>

In [168]:
tf.sqrt(b)

<tf.Tensor: id=639, shape=(2, 2), dtype=float32, numpy=
array([[1.4142135, 1.4142135],
       [1.4142135, 1.4142135]], dtype=float32)>

@ == matmul

In [172]:
a = tf.ones([4, 4, 2, 3])
b = tf.fill([4,4, 3, 5], 2.)
print(a.shape)
print(b.shape)

(4, 4, 2, 3)
(4, 4, 3, 5)


In [175]:
# @ 矩阵相乘，最后两维看作是一个矩阵的行和列 
c = a@b
c.shape

TensorShape([4, 4, 2, 5])

In [176]:
c = tf.matmul(a, b)
c.shape

TensorShape([4, 4, 2, 5])

Y = X @ W + b

In [177]:
x = tf.ones([4, 2])
W = tf.ones([2, 1])
b = tf.constant(0.1)
x@W+b

<tf.Tensor: id=668, shape=(4, 1), dtype=float32, numpy=
array([[2.1],
       [2.1],
       [2.1],
       [2.1]], dtype=float32)>

In [179]:
out = tf.nn.relu(x@W+b)
out

<tf.Tensor: id=675, shape=(4, 1), dtype=float32, numpy=
array([[2.1],
       [2.1],
       [2.1],
       [2.1]], dtype=float32)>

In [181]:
w1 = tf.Variable(tf.random.truncated_normal([784, 512], stddev=0.1))
tf.is_tensor(w1)
b1 = tf.Variable(tf.zeros[512])
for step, (x, y) in enumerate()

True

Hellow World in Deeplearning: MNIST

1、加载数据

2、训练：

    前项
    
    loss
    
    计算梯度
    
    bp更新
    
    

In [86]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import datasets
import os

In [87]:
# 加载数据
# x: [60k, 28, 28]
# y:[60k]
(x, y), _ = datasets.mnist.load_data()


In [88]:
x.shape, y.shape

((60000, 28, 28), (60000,))

In [91]:
# x[0-255] => [0-1.]
x = tf.convert_to_tensor(x, dtype=tf.float32) / 255.
y = tf.convert_to_tensor(y, dtype=tf.int32)
print(tf.reduce_min(x), tf.reduce_max(x))
print(tf.reduce_min(y), tf.reduce_max(y))

tf.Tensor(0.0, shape=(), dtype=float32) tf.Tensor(1.0, shape=(), dtype=float32)
tf.Tensor(0, shape=(), dtype=int32) tf.Tensor(9, shape=(), dtype=int32)


In [92]:
#将加载进来的数据打包成网络可用的batch
train_db = tf.data.Dataset.from_tensor_slices((x, y))
train_db = train_db.batch(128)
train_iter = iter(train_db)
sample = next(train_iter)
print(sample[0].shape, sample[1].shape)

(128, 28, 28) (128,)


In [93]:
# 网络参数初始化
# [b, 784] => [b, 256] => [b, 128] => [b, 10]
w1 = tf.Variable(tf.random.truncated_normal([784, 256], stddev=0.1))
b1 = tf.Variable(tf.zeros([256]))
w2 = tf.Variable(tf.random.truncated_normal([256, 128], stddev=0.1))
b2 = tf.Variable(tf.zeros([128]))
w3 = tf.Variable(tf.random.truncated_normal([128, 10], stddev=0.1))
b3 = tf.Variable(tf.zeros([10]))
lr = 1e-3

for epoch in range(10):
    for step, (x, y) in enumerate(train_db):
        # x [b, 28, 28] => [b, 784]
        x = tf.reshape(x, [-1, 784])
        
        with tf.GradientTape() as tape:
            # forward
            # [b, 784] => [b, 256]
            h1 = x@w1 + b1
            h1 = tf.nn.relu(h1)

            # [b, 256] => [b, 128]
            h2 = h1@w2 + b2

            # [b, 128] => [b, 10]
            h2 = tf.nn.relu(h2)

            out = h2@w3 + b3

            # compute loss
            # out :[b, 10]
            y_onehot = tf.one_hot(y, depth=10)

            loss = tf.square(y_onehot - out)
            loss = tf.reduce_mean(loss)

        # compute gradients
        grads = tape.gradient(loss, [w1, b1, w2, b2, w3, b3])
        # print(grads)
        # update
        w1.assign_sub(lr * grads[0])
        b1.assign_sub(lr * grads[1])
        w2.assign_sub(lr * grads[2])
        b2.assign_sub(lr * grads[3])      
        w3.assign_sub(lr * grads[4])
        b3.assign_sub(lr * grads[5])   
        
        if step % 100 == 0:
            print(epoch, step, 'loss:', float(loss))
        
        
        


0 0 loss: 0.41730421781539917
0 100 loss: 0.20625467598438263
0 200 loss: 0.18165622651576996
0 300 loss: 0.17070910334587097
0 400 loss: 0.17376823723316193
1 0 loss: 0.15751643478870392
1 100 loss: 0.1607750654220581
1 200 loss: 0.1503896862268448
1 300 loss: 0.14429600536823273
1 400 loss: 0.14638476073741913
2 0 loss: 0.13458187878131866
2 100 loss: 0.14115481078624725
2 200 loss: 0.13245388865470886
2 300 loss: 0.12659813463687897
2 400 loss: 0.12872543931007385
3 0 loss: 0.11911433935165405
3 100 loss: 0.12767282128334045
3 200 loss: 0.11997254192829132
3 300 loss: 0.11415383964776993
3 400 loss: 0.11628677695989609
4 0 loss: 0.1080213338136673
4 100 loss: 0.11773601919412613
4 200 loss: 0.11073829978704453
4 300 loss: 0.1050143837928772
4 400 loss: 0.10700678825378418
5 0 loss: 0.09960345178842545
5 100 loss: 0.11008040606975555
5 200 loss: 0.10364830493927002
5 300 loss: 0.09804201126098633
5 400 loss: 0.09982790052890778
6 0 loss: 0.09306903183460236
6 100 loss: 0.104001738131

Merge and split

In [203]:
a = tf.ones([4, 35, 8])
b = tf.ones([2, 35, 8])

c = tf.concat([a, b], axis=0)
c.shape

TensorShape([6, 35, 8])

In [206]:
# tf.stack : 创造一个新的维度
print(a.shape)
print(b.shape)

(4, 35, 8)
(2, 35, 8)


In [214]:
a = tf.ones([4, 35, 8])
b = tf.ones([4, 35, 8])

c = tf.stack([a, b], axis=1)
c.shape

TensorShape([4, 2, 35, 8])

In [220]:
aa, bb = tf.unstack(c,axis=1)
print(aa.shape)
print(bb.shape)

(4, 35, 8)
(4, 35, 8)


tf.norm

In [221]:
a = tf.ones([2, 2])
# 默认求L2范数
tf.norm(a)

<tf.Tensor: id=876366, shape=(), dtype=float32, numpy=2.0>

In [222]:
# L1范数
tf.norm(a, ord=1)

<tf.Tensor: id=876371, shape=(), dtype=float32, numpy=4.0>

In [223]:
# 某一个轴的L1范数
tf.norm(a, ord=1, axis=1)

<tf.Tensor: id=876376, shape=(2,), dtype=float32, numpy=array([2., 2.], dtype=float32)>

reduce_min/max/mean

In [224]:
a = tf.random.normal([4, 10])
# 所有数求平均
tf.reduce_mean(a)
# 按行求最大
tf.reduce_max(a, axis=1)
# 按列求最小
tf.reduce_min(a, axis=0)

<tf.Tensor: id=876385, shape=(10,), dtype=float32, numpy=
array([-0.9367147 , -0.4399184 , -0.84076613, -0.4720565 , -1.9700844 ,
       -1.1336707 , -1.9769382 , -1.5289234 , -0.9495128 , -0.2790423 ],
      dtype=float32)>

argmax
argmin

In [225]:
a.shape

TensorShape([4, 10])

In [230]:
# 默认按列得到取值最大的索引
b = tf.argmax(a)
b.shape

TensorShape([10])

tf.equal

In [232]:
a = tf.constant([1,2,3,4,5])
b = tf.range(5)
print(a)
print(b)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int32)


In [233]:
tf.equal(a, b)

<tf.Tensor: id=876411, shape=(5,), dtype=bool, numpy=array([False, False, False, False, False])>

accuracy

In [237]:
out = tf.constant([[0.1, 0.2, 0.7],
                  [0.9, 0.05, 0.05]], dtype=tf.float32)

pred = tf.cast(tf.argmax(out, axis=1), dtype=tf.int32)
pred

<tf.Tensor: id=876424, shape=(2,), dtype=int32, numpy=array([2, 0])>

In [241]:
y = tf.constant([2,1])

correct = tf.reduce_sum(tf.cast(tf.equal(pred, y), tf.int32))
print(correct)
correct = correct / 2
correct

tf.Tensor(1, shape=(), dtype=int32)


<tf.Tensor: id=876464, shape=(), dtype=float64, numpy=0.5>

tf.unique

tensor去重

In [245]:
a = tf.constant([4, 2, 2,4,3])
# 返回两个tensor， b :去重后的结果 c: 索引，可由此索引和b还原原来的数

b, c = tf.unique(a)
b, c

(<tf.Tensor: id=876473, shape=(3,), dtype=int32, numpy=array([4, 2, 3])>,
 <tf.Tensor: id=876474, shape=(5,), dtype=int32, numpy=array([0, 1, 1, 0, 2])>)

In [248]:
a_ = tf.gather(b, [c])
tf.equal(a, a_)

<tf.Tensor: id=876487, shape=(1, 5), dtype=bool, numpy=array([[ True,  True,  True,  True,  True]])>

tf.sort

tf.argsort

In [255]:
a = tf.random.shuffle(tf.range(5))
a


<tf.Tensor: id=876555, shape=(5,), dtype=int32, numpy=array([2, 4, 1, 0, 3])>

In [256]:
tf.sort(a)
a

<tf.Tensor: id=876555, shape=(5,), dtype=int32, numpy=array([2, 4, 1, 0, 3])>

In [257]:
tf.argsort(a)

<tf.Tensor: id=876580, shape=(5,), dtype=int32, numpy=array([3, 2, 0, 4, 1])>

In [260]:
a = tf.random.uniform([3, 3], maxval=10, dtype=tf.int32)
a = tf.sort(a)
a

<tf.Tensor: id=876636, shape=(3, 3), dtype=int32, numpy=
array([[3, 7, 8],
       [1, 3, 4],
       [3, 4, 5]])>

In [261]:
tf.argsort(a)

<tf.Tensor: id=876648, shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])>

Top_k

In [262]:
a


<tf.Tensor: id=876636, shape=(3, 3), dtype=int32, numpy=
array([[3, 7, 8],
       [1, 3, 4],
       [3, 4, 5]])>

In [270]:

res = tf.math.top_k(a, 2)
res.values


<tf.Tensor: id=876681, shape=(3, 2), dtype=int32, numpy=
array([[8, 7],
       [4, 3],
       [5, 4]])>

In [268]:
res.indices


<tf.Tensor: id=876663, shape=(3, 2), dtype=int32, numpy=
array([[2, 1],
       [2, 1],
       [2, 1]])>

计算top_k正确率

In [271]:
tf.random.set_seed(2467)

def accuracy(output, target, topk=(1,)):
    maxk = max(topk)
    batch_size = target.shape[0]

    pred = tf.math.top_k(output, maxk).indices
    pred = tf.transpose(pred, perm=[1, 0])
    target_ = tf.broadcast_to(target, pred.shape)
    # [10, b]
    correct = tf.equal(pred, target_)

    res = []
    for k in topk:
        correct_k = tf.cast(tf.reshape(correct[:k], [-1]), dtype=tf.float32)
        correct_k = tf.reduce_sum(correct_k)
        acc = float(correct_k* (100.0 / batch_size) )
        res.append(acc)

    return res



output = tf.random.normal([10, 6])
output = tf.math.softmax(output, axis=1)
target = tf.random.uniform([10], maxval=6, dtype=tf.int32)
print('prob:', output.numpy())
pred = tf.argmax(output, axis=1)
print('pred:', pred.numpy())
print('label:', target.numpy())

acc = accuracy(output, target, topk=(1,2,3,4,5,6))
print('top-1-6 acc:', acc)



prob: [[0.25310278 0.21715644 0.16043882 0.13088997 0.04334083 0.19507109]
 [0.05892418 0.04548917 0.00926314 0.14529602 0.66777605 0.07325139]
 [0.09742808 0.08304427 0.07460099 0.04067177 0.626185   0.07806987]
 [0.20478569 0.12294924 0.12010485 0.13751231 0.36418733 0.05046057]
 [0.11872064 0.31072393 0.12530336 0.1552888  0.2132587  0.07670452]
 [0.01519807 0.09672114 0.1460476  0.00934331 0.5649092  0.16778067]
 [0.04199061 0.18141054 0.06647632 0.6006175  0.03198383 0.07752118]
 [0.09226219 0.2346089  0.13022321 0.16295874 0.05362028 0.3263266 ]
 [0.07019574 0.0861177  0.10912605 0.10521299 0.2152082  0.4141393 ]
 [0.01882887 0.26597694 0.19122466 0.24109262 0.14920162 0.13367532]]
pred: [0 4 4 4 1 4 3 5 5 1]
label: [0 2 3 4 2 4 2 3 5 5]
top-1-6 acc: [40.0, 40.0, 50.0, 70.0, 80.0, 100.0]


tf.pad


In [272]:
a = tf.reshape(tf.range(9), [3,3])
a


<tf.Tensor: id=876785, shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])>

In [273]:
tf.pad(a, [[1,1], [1,0]])

<tf.Tensor: id=876788, shape=(5, 4), dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 0, 1, 2],
       [0, 3, 4, 5],
       [0, 6, 7, 8],
       [0, 0, 0, 0]])>

tf.tile

In [274]:
a


<tf.Tensor: id=876785, shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])>

In [275]:
tf.tile(a, [1,2])

<tf.Tensor: id=876792, shape=(3, 6), dtype=int32, numpy=
array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])>

tf.maximum(a, b) : 返回a,b中的最大值

tf.minimum


tf.clip_by_value

In [277]:
a = tf.range(10)
a

<tf.Tensor: id=876801, shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [285]:
b = tf.random.uniform([10], minval=0, maxval=10, dtype=tf.int32)
b

<tf.Tensor: id=876839, shape=(10,), dtype=int32, numpy=array([1, 7, 4, 5, 4, 7, 9, 9, 4, 3])>

In [286]:
tf.maximum(a, b)

<tf.Tensor: id=876841, shape=(10,), dtype=int32, numpy=array([1, 7, 4, 5, 4, 7, 9, 9, 8, 9])>

In [287]:
tf.maximum(a, 2)

<tf.Tensor: id=876844, shape=(10,), dtype=int32, numpy=array([2, 2, 2, 3, 4, 5, 6, 7, 8, 9])>

In [288]:
tf.minimum(a, 3)

<tf.Tensor: id=876847, shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 3, 3, 3, 3, 3, 3])>

In [289]:
tf.clip_by_value(a, 2, 8)

<tf.Tensor: id=876852, shape=(10,), dtype=int32, numpy=array([2, 2, 2, 3, 4, 5, 6, 7, 8, 8])>

tf.clip_by_norm

In [290]:
a = tf.random.normal([2, 2], mean=10)
a

<tf.Tensor: id=876859, shape=(2, 2), dtype=float32, numpy=
array([[ 9.532964 , 10.01408  ],
       [10.0157385,  9.255953 ]], dtype=float32)>

In [291]:
tf.norm(a)

<tf.Tensor: id=876865, shape=(), dtype=float32, numpy=19.420269>

In [292]:
aa = tf.clip_by_norm(a, 5)
aa

<tf.Tensor: id=876883, shape=(2, 2), dtype=float32, numpy=
array([[2.454385 , 2.5782547],
       [2.5786817, 2.383065 ]], dtype=float32)>

In [293]:
tf.norm(aa)

<tf.Tensor: id=876889, shape=(), dtype=float32, numpy=5.0>

In [308]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import datasets, layers, optimizers

(x, y), _ = datasets.mnist.load_data()
# [b, 28, 28, 3]
x = tf.convert_to_tensor(x, dtype=tf.float32) / 127.5 - 1
# [b] => [b, 10]
y = tf.convert_to_tensor(y)
y = tf.one_hot(y, depth=10)

# [b, 28, 28, 3]
# [b, 10]
train_db = tf.data.Dataset.from_tensor_slices((x, y)).batch(128)
x, y = next(iter(train_db))
# print(x.shape, y.shape)
# 784 => 512
w1 = tf.Variable(tf.random.truncated_normal([784, 512], stddev=0.1))
b1 = tf.Variable(tf.zeros([512]))
w2 = tf.Variable(tf.random.truncated_normal([512, 256], stddev=0.1))
b2 = tf.Variable(tf.zeros([256]))
# [b, 10]
w3 = tf.Variable(tf.random.truncated_normal([256, 10], stddev=0.1))
b3 = tf.Variable(tf.zeros([10]))

optimizer = optimizers.SGD(lr=0.01)

for step, (x,y) in enumerate(train_db):
    x = tf.reshape(x, [-1, 784])
    
    with tf.GradientTape() as tape:
        # layer1.
        h1 = x @ w1 + b1
        h1 = tf.nn.relu(h1)
        # layer2
        h2 = h1 @ w2 + b2
        h2 = tf.nn.relu(h2)
        # output
        logit = h2 @ w3 + b3
        # out = tf.nn.relu(out)
        
        # compute loss
        loss = tf.reduce_mean(tf.losses.categorical_crossentropy(y, logit, from_logits=True))
        
    # computer gradient
    grads = tape.gradient(loss, [w1, b1, w2, b2, w3, b3])
    grads, _ = tf.clip_by_global_norm(grads, 5)
    
    # update
    optimizer.apply_gradients(zip(grads, [w1, b1, w2, b2, w3, b3]))
    
    if step % 100 == 0:
        print(step, 'loss:', float(loss))


0 loss: 4.532197952270508
100 loss: 0.6432369947433472
200 loss: 0.3012292683124542
300 loss: 0.4071490466594696
400 loss: 0.43749818205833435


tf.data.Dataset

In [312]:
# from_tensor_slices()
(x, y), (x_test, y_test) = tf.keras.datasets.mnist.load_data()
db = tf.data.Dataset.from_tensor_slices((x_test, y_test))
next(iter(db))[0].shape

TensorShape([28, 28])

In [313]:
# .shuffle
db = db.shuffle(1000)

In [314]:
# .map
def preprocess(x, y):
    x = tf.cast(x, dtype=tf.float32)/ 255.
    y = tf.cast(y, tf.int32)
    y = tf.one_hot(y, depth=10)
    return x, y
db2 = db.map(preprocess)
res = next(iter(db2))
res[0].shape, res[1].shape

(TensorShape([28, 28]), TensorShape([10]))

In [315]:
res[1][:2]

<tf.Tensor: id=2883510, shape=(2,), dtype=float32, numpy=array([0., 0.], dtype=float32)>

In [316]:
# .batch
db3 = db2.batch(32)
res = next(iter(db3))
res[0].shape, res[1].shape

(TensorShape([32, 28, 28]), TensorShape([32, 10]))

写一遍比较完整的mnist


In [329]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import datasets, optimizers

# 图像预处理
def preprocess(x, y):
    x = tf.reshape(x, [-1, 28*28])
    x = tf.cast(x, dtype=tf.float32) / 255.
    y = tf.one_hot(y, depth=10)
    return x, y

# 导入数据:
(x, y), (x_test, y_test) = datasets.mnist.load_data()
train_db = tf.data.Dataset.from_tensor_slices((x, y))
train_db = train_db.shuffle(10000).batch(128).map(preprocess)
#t1 = next(iter(train_db))
#t1[0].shape, t1[1].shape

test_db = tf.data.Dataset.from_tensor_slices((x_test, y_test))
test_db = test_db.batch(128).map(preprocess)

w1 = tf.Variable(tf.random.truncated_normal([784, 512],stddev=0.1))
b1 = tf.Variable(tf.zeros([512]))
w2 = tf.Variable(tf.random.truncated_normal([512, 256],stddev=0.1))
b2 = tf.Variable(tf.zeros([256]))
w3 = tf.Variable(tf.random.truncated_normal([256, 10],stddev=0.1))
b3 = tf.Variable(tf.zeros([10]))

optimizer = optimizers.SGD(learning_rate=0.01)
for epoch in range(10):
    for step,(x, y) in enumerate(train_db):
        with tf.GradientTape() as tape:
            h1 = x@w1 + b1
            h1 = tf.nn.relu(h1)

            h2 = h1@w2 + b2
            h2 = tf.nn.relu(h2)

            logit = h2@w3 + b3

            # compute loss
            loss = tf.losses.categorical_crossentropy(y, logit, from_logits=True)
            loss = tf.reduce_mean(loss)
            # compute grads
            grads = tape.gradient(loss, [w1, b1, w2, b2, w3, b3])
        
        # bp
        optimizer.apply_gradients(zip(grads, [w1, b1, w2, b2, w3, b3]))
        if step % 100 == 0:
            print(epoch, step, 'loss: ', loss.numpy())
            
        
        if step % 500 == 0:
            total, total_correct = 0, 0
            for step, (x_test, y_test) in enumerate(test_db):
                
                h1 = x_test@w1 + b1               
                h1 = tf.nn.relu(h1)
                h2 = h1@w2 + b2
                h2 = tf.nn.relu(h2)
                # [b, 10]
                logit = h2@w3 + b3
                
                pred = tf.argmax(logit, axis=1)
                # y [b, 10] => [b]
                # print(y_test.shape)
                y_test = tf.argmax(y_test, axis=1)
                
                correct = tf.cast(tf.equal(pred, y_test) , dtype=tf.int32)
                correct = tf.reduce_sum(correct).numpy()
                total_correct += correct
                total += x.shape[0]
                
            print(step, 'Evaluate Acc:', total_correct/total)
                
                    
            

        

0 0 loss:  3.1128874
78 Evaluate Acc: 0.09384889240506329
0 100 loss:  1.0359747
0 200 loss:  0.6256821
0 300 loss:  0.6009066
0 400 loss:  0.47016668
1 0 loss:  0.4242708
78 Evaluate Acc: 0.872626582278481
1 100 loss:  0.4523915
1 200 loss:  0.35190895
1 300 loss:  0.40619582
1 400 loss:  0.3366956
2 0 loss:  0.29382175
78 Evaluate Acc: 0.8958662974683544
2 100 loss:  0.33402175
2 200 loss:  0.30737653
2 300 loss:  0.34209058
2 400 loss:  0.28476316
3 0 loss:  0.236809
78 Evaluate Acc: 0.906942246835443
3 100 loss:  0.26859537
3 200 loss:  0.2910796
3 300 loss:  0.3049006
3 400 loss:  0.25388867
4 0 loss:  0.20151255
78 Evaluate Acc: 0.914754746835443
4 100 loss:  0.22604337
4 200 loss:  0.2810444
4 300 loss:  0.27894944
4 400 loss:  0.23238349
5 0 loss:  0.17618316
78 Evaluate Acc: 0.9181170886075949
5 100 loss:  0.19604462
5 200 loss:  0.2724632
5 300 loss:  0.25895
5 400 loss:  0.21576703
6 0 loss:  0.15659714
78 Evaluate Acc: 0.921875
6 100 loss:  0.17376609
6 200 loss:  0.2642697

全连接层

In [330]:
x = tf.random.normal([4, 784])
net = tf.keras.layers.Dense(512)
out = net(x)
out.shape

TensorShape([4, 512])

In [333]:
net.kernel.shape, net.bias.shape

(TensorShape([784, 512]), TensorShape([512]))

In [340]:
net = tf.keras.layers.Dense(10)


In [341]:
net.get_weights()

[]

In [342]:
net.weights

[]

In [344]:
x = tf.random.normal([2, 3])
model = keras.Sequential([
        keras.layers.Dense(2, activation='relu'),
        keras.layers.Dense(2, activation='relu'),
        keras.layers.Dense(2)])

model.build(input_shape=(None, 4))
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_5 (Dense)              multiple                  10        
_________________________________________________________________
dense_6 (Dense)              multiple                  6         
_________________________________________________________________
dense_7 (Dense)              multiple                  6         
Total params: 22
Trainable params: 22
Non-trainable params: 0
_________________________________________________________________


In [350]:
for p in model.trainable_variables:
    print(p.name, p.shape)

dense_5/kernel:0 (4, 2)
dense_5/bias:0 (2,)
dense_6/kernel:0 (2, 2)
dense_6/bias:0 (2,)
dense_7/kernel:0 (2, 2)
dense_7/bias:0 (2,)


sigmoid and softmax

In [356]:
a = tf.linspace(-2., 2., 5)
a

<tf.Tensor: id=4699107, shape=(5,), dtype=float32, numpy=array([-2., -1.,  0.,  1.,  2.], dtype=float32)>

In [357]:
tf.sigmoid(a)

<tf.Tensor: id=4699109, shape=(5,), dtype=float32, numpy=
array([0.11920291, 0.26894143, 0.5       , 0.7310586 , 0.880797  ],
      dtype=float32)>

In [358]:
tf.nn.softmax(a)

<tf.Tensor: id=4699111, shape=(5,), dtype=float32, numpy=
array([0.01165623, 0.03168492, 0.08612854, 0.23412167, 0.6364086 ],
      dtype=float32)>

tf.losses.categorical_crossentropy

In [359]:
tf.losses.categorical_crossentropy([0,1,0, 0], [0.1,0.1,0.8, 0])

<tf.Tensor: id=4699130, shape=(), dtype=float32, numpy=2.3025851>

tf.losses.binary_crossentropy

In [361]:
tf.losses.binary_crossentropy([1,1,0],[0.1, 0.2, 0.3])

<tf.Tensor: id=4699184, shape=(), dtype=float32, numpy=1.4228988>

GradientTape

In [365]:
w = tf.Variable(2.)
x = tf.constant(11.)
with tf.GradientTape() as tape:
    tape.watch([w])
    y = x * w
grad = tape.gradient(y, [w])
grad

[<tf.Tensor: id=4699225, shape=(), dtype=float32, numpy=11.0>]

In [377]:
import tensorflow as tf 

#x = tf.Variable(1.)
#w1 = tf.Variable(2.)
#b1 = tf.Variable(1.)
#w2 = tf.Variable(2.)
#b2 = tf.Variable(1.)

x = tf.constant(1.)
w1 = tf.constant(2.)
b1 = tf.constant(1.)
w2 = tf.constant(2.)
b2 = tf.constant(1.)
with tf.GradientTape(persistent=True) as tape:

    #tape.watch([w1, b1, w2, b2])
    tape.watch([w1, b1, w2, b2])
    
    y1 = x * w1 + b1
    y2 = y1 * w2 + b2

dy2_dy1 = tape.gradient(y2, [y1])
dy1_dw1 = tape.gradient(y1, [w1])
dy2_dw1 = tape.gradient(y2, [w1])


#print(dy2_dy1 * dy1_dw1)
print(dy2_dw1)

[<tf.Tensor: id=4699517, shape=(), dtype=float32, numpy=2.0>]


fashionMNIST实战

In [380]:
import tensorflow as tf
from    tensorflow import keras
from    tensorflow.keras import datasets, layers, optimizers, Sequential

import  os

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

def preprocess(x, y):

    x = tf.cast(x, dtype=tf.float32) / 255.
    y = tf.cast(y, dtype=tf.int32)
    return x,y


(x, y), (x_test, y_test) = datasets.fashion_mnist.load_data()
print(x.shape, y.shape)

batchsz = 128

db = tf.data.Dataset.from_tensor_slices((x,y))
db = db.map(preprocess).shuffle(10000).batch(batchsz)

db_test = tf.data.Dataset.from_tensor_slices((x_test,y_test))
db_test = db_test.map(preprocess).batch(batchsz)

db_iter = iter(db)
sample = next(db_iter)
print('batch:', sample[0].shape, sample[1].shape)


model = Sequential([
    layers.Dense(256, activation=tf.nn.relu), # [b, 784] => [b, 256]
    layers.Dense(128, activation=tf.nn.relu), # [b, 256] => [b, 128]
    layers.Dense(64, activation=tf.nn.relu), # [b, 128] => [b, 64]
    layers.Dense(32, activation=tf.nn.relu), # [b, 64] => [b, 32]
    layers.Dense(10) # [b, 32] => [b, 10], 330 = 32*10 + 10
])
model.build(input_shape=[None, 28*28])
model.summary()
# w = w - lr*grad
optimizer = optimizers.Adam(lr=1e-3)

def main():


    for epoch in range(1):


        for step, (x,y) in enumerate(db):

            # x: [b, 28, 28] => [b, 784]
            # y: [b]
            x = tf.reshape(x, [-1, 28*28])

            with tf.GradientTape() as tape:
                # [b, 784] => [b, 10]
                logits = model(x)
                y_onehot = tf.one_hot(y, depth=10)
                # [b]
                loss_mse = tf.reduce_mean(tf.losses.MSE(y_onehot, logits))
                loss_ce = tf.losses.categorical_crossentropy(y_onehot, logits, from_logits=True)
                loss_ce = tf.reduce_mean(loss_ce)

            grads = tape.gradient(loss_ce, model.trainable_variables)
            optimizer.apply_gradients(zip(grads, model.trainable_variables))


            if step % 100 == 0:
                print(epoch, step, 'loss:', float(loss_ce), float(loss_mse))


        # test
        total_correct = 0
        total_num = 0
        for x,y in db_test:

            # x: [b, 28, 28] => [b, 784]
            # y: [b]
            x = tf.reshape(x, [-1, 28*28])
            # [b, 10]
            logits = model(x)
            # logits => prob, [b, 10]
            prob = tf.nn.softmax(logits, axis=1)
            # [b, 10] => [b], int64
            pred = tf.argmax(prob, axis=1)
            pred = tf.cast(pred, dtype=tf.int32)
            # pred:[b]
            # y: [b]
            # correct: [b], True: equal, False: not equal
            correct = tf.equal(pred, y)
            correct = tf.reduce_sum(tf.cast(correct, dtype=tf.int32))

            total_correct += int(correct)
            total_num += x.shape[0]

        acc = total_correct / total_num
        print(epoch, 'test acc:', acc)







if __name__ == '__main__':
    main()

(60000, 28, 28) (60000,)
batch: (128, 28, 28) (128,)
Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_18 (Dense)             multiple                  200960    
_________________________________________________________________
dense_19 (Dense)             multiple                  32896     
_________________________________________________________________
dense_20 (Dense)             multiple                  8256      
_________________________________________________________________
dense_21 (Dense)             multiple                  2080      
_________________________________________________________________
dense_22 (Dense)             multiple                  330       
Total params: 244,522
Trainable params: 244,522
Non-trainable params: 0
_________________________________________________________________
0 0 loss: 2.3149633407592773 0.15233640372753143
0 100 loss: 

Tensorboard

1、建立一个summary

summary_writer = tf.summary.create_file_writer(log_dir

2、喂scalar

with summary_writer.as_default():

    tf.summary.scalar('loss', float(loss), step=epoch)
    
    tf.summary.scalar('acc',float(train_accurary),step=epoch)
    
3、喂image

    tf.summary.image('Training sample', sample_img, step=0)

4、run: tensorboard --logdir log_dir

In [382]:
import  tensorflow as tf
from    tensorflow.keras import datasets, layers, optimizers, Sequential, metrics
import  datetime
from    matplotlib import pyplot as plt
import  io

def preprocess(x, y):

    x = tf.cast(x, dtype=tf.float32) / 255.
    y = tf.cast(y, dtype=tf.int32)

    return x,y


def plot_to_image(figure):
  """Converts the matplotlib plot specified by 'figure' to a PNG image and
  returns it. The supplied figure is closed and inaccessible after this call."""
  # Save the plot to a PNG in memory.
  buf = io.BytesIO()
  plt.savefig(buf, format='png')
  # Closing the figure prevents it from being displayed directly inside
  # the notebook.
  plt.close(figure)
  buf.seek(0)
  # Convert PNG buffer to TF image
  image = tf.image.decode_png(buf.getvalue(), channels=4)
  # Add the batch dimension
  image = tf.expand_dims(image, 0)
  return image

def image_grid(images):
  """Return a 5x5 grid of the MNIST images as a matplotlib figure."""
  # Create a figure to contain the plot.
  figure = plt.figure(figsize=(10,10))
  for i in range(25):
    # Start next subplot.
    plt.subplot(5, 5, i + 1, title='name')
    plt.xticks([])
    plt.yticks([])
    plt.grid(False)
    plt.imshow(images[i], cmap=plt.cm.binary)
  
  return figure



batchsz = 128
(x, y), (x_val, y_val) = datasets.mnist.load_data()
print('datasets:', x.shape, y.shape, x.min(), x.max())



db = tf.data.Dataset.from_tensor_slices((x,y))
db = db.map(preprocess).shuffle(60000).batch(batchsz).repeat(10)

ds_val = tf.data.Dataset.from_tensor_slices((x_val, y_val))
ds_val = ds_val.map(preprocess).batch(batchsz, drop_remainder=True) 




network = Sequential([layers.Dense(256, activation='relu'),
                     layers.Dense(128, activation='relu'),
                     layers.Dense(64, activation='relu'),
                     layers.Dense(32, activation='relu'),
                     layers.Dense(10)])
network.build(input_shape=(None, 28*28))
network.summary()

optimizer = optimizers.Adam(lr=0.01)



current_time = datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
log_dir = 'logs/' + current_time
summary_writer = tf.summary.create_file_writer(log_dir) 

# get x from (x,y)
sample_img = next(iter(db))[0]
# get first image instance
sample_img = sample_img[0]
sample_img = tf.reshape(sample_img, [1, 28, 28, 1])
with summary_writer.as_default():
    tf.summary.image("Training sample:", sample_img, step=0)

for step, (x,y) in enumerate(db):

    with tf.GradientTape() as tape:
        # [b, 28, 28] => [b, 784]
        x = tf.reshape(x, (-1, 28*28))
        # [b, 784] => [b, 10]
        out = network(x)
        # [b] => [b, 10]
        y_onehot = tf.one_hot(y, depth=10) 
        # [b]
        loss = tf.reduce_mean(tf.losses.categorical_crossentropy(y_onehot, out, from_logits=True))

 

    grads = tape.gradient(loss, network.trainable_variables)
    optimizer.apply_gradients(zip(grads, network.trainable_variables))


    if step % 100 == 0:

        print(step, 'loss:', float(loss))
        with summary_writer.as_default(): 
            tf.summary.scalar('train-loss', float(loss), step=step) 

    # evaluate
    if step % 500 == 0:
        total, total_correct = 0., 0

        for _, (x, y) in enumerate(ds_val):  
            # [b, 28, 28] => [b, 784]
            x = tf.reshape(x, (-1, 28*28))
            # [b, 784] => [b, 10]
            out = network(x) 
            # [b, 10] => [b] 
            pred = tf.argmax(out, axis=1) 
            pred = tf.cast(pred, dtype=tf.int32)
            # bool type 
            correct = tf.equal(pred, y)
            # bool tensor => int tensor => numpy
            total_correct += tf.reduce_sum(tf.cast(correct, dtype=tf.int32)).numpy()
            total += x.shape[0]

        print(step, 'Evaluate Acc:', total_correct/total)

        
        # print(x.shape) 
        val_images = x[:25]
        val_images = tf.reshape(val_images, [-1, 28, 28, 1])
        with summary_writer.as_default():
            tf.summary.scalar('test-acc', float(total_correct/total), step=step)
            tf.summary.image("val-onebyone-images:", val_images, max_outputs=25, step=step)
            
            val_images = tf.reshape(val_images, [-1, 28, 28])
            figure  = image_grid(val_images)
            tf.summary.image('val-images:', plot_to_image(figure), step=step)

datasets: (60000, 28, 28) (60000,) 0 255
Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_23 (Dense)             multiple                  200960    
_________________________________________________________________
dense_24 (Dense)             multiple                  32896     
_________________________________________________________________
dense_25 (Dense)             multiple                  8256      
_________________________________________________________________
dense_26 (Dense)             multiple                  2080      
_________________________________________________________________
dense_27 (Dense)             multiple                  330       
Total params: 244,522
Trainable params: 244,522
Non-trainable params: 0
_________________________________________________________________
0 loss: 2.277104616165161
0 Evaluate Acc: 0.1877003205128205
100 loss: 0.

Keras.Metrics

1、定义一把尺子

acc_meter = metrics.Accuracy()

loss_meter = metrics.Mean()

2、训练或测试过程中不断更新

loss_meter.update_state(loss)

acc_meter.update_state(y, pred)

3、输出结果(输出的是开始记录以来的平均值)


loss_meter.result().numpy()


acc_meter.result().numpy()


4、 如果原来的记录不要了的话，记得清空

reset_states

In [383]:
import  tensorflow as tf
from    tensorflow.keras import datasets, layers, optimizers, Sequential, metrics


def preprocess(x, y):

    x = tf.cast(x, dtype=tf.float32) / 255.
    y = tf.cast(y, dtype=tf.int32)

    return x,y


batchsz = 128
(x, y), (x_val, y_val) = datasets.mnist.load_data()
print('datasets:', x.shape, y.shape, x.min(), x.max())



db = tf.data.Dataset.from_tensor_slices((x,y))
db = db.map(preprocess).shuffle(60000).batch(batchsz).repeat(10)

ds_val = tf.data.Dataset.from_tensor_slices((x_val, y_val))
ds_val = ds_val.map(preprocess).batch(batchsz) 




network = Sequential([layers.Dense(256, activation='relu'),
                     layers.Dense(128, activation='relu'),
                     layers.Dense(64, activation='relu'),
                     layers.Dense(32, activation='relu'),
                     layers.Dense(10)])
network.build(input_shape=(None, 28*28))
network.summary()

optimizer = optimizers.Adam(lr=0.01)

acc_meter = metrics.Accuracy()
loss_meter = metrics.Mean()


for step, (x,y) in enumerate(db):

    with tf.GradientTape() as tape:
        # [b, 28, 28] => [b, 784]
        x = tf.reshape(x, (-1, 28*28))
        # [b, 784] => [b, 10]
        out = network(x)
        # [b] => [b, 10]
        y_onehot = tf.one_hot(y, depth=10) 
        # [b]
        loss = tf.reduce_mean(tf.losses.categorical_crossentropy(y_onehot, out, from_logits=True))

        loss_meter.update_state(loss)

 

    grads = tape.gradient(loss, network.trainable_variables)
    optimizer.apply_gradients(zip(grads, network.trainable_variables))


    if step % 100 == 0:

        print(step, 'loss:', loss_meter.result().numpy()) 
        loss_meter.reset_states()


    # evaluate
    if step % 500 == 0:
        total, total_correct = 0., 0
        acc_meter.reset_states()

        for step, (x, y) in enumerate(ds_val): 
            # [b, 28, 28] => [b, 784]
            x = tf.reshape(x, (-1, 28*28))
            # [b, 784] => [b, 10]
            out = network(x) 


            # [b, 10] => [b] 
            pred = tf.argmax(out, axis=1) 
            pred = tf.cast(pred, dtype=tf.int32)
            # bool type 
            correct = tf.equal(pred, y)
            # bool tensor => int tensor => numpy
            total_correct += tf.reduce_sum(tf.cast(correct, dtype=tf.int32)).numpy()
            total += x.shape[0]

            acc_meter.update_state(y, pred)


        print(step, 'Evaluate Acc:', total_correct/total, acc_meter.result().numpy())


datasets: (60000, 28, 28) (60000,) 0 255
Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_28 (Dense)             multiple                  200960    
_________________________________________________________________
dense_29 (Dense)             multiple                  32896     
_________________________________________________________________
dense_30 (Dense)             multiple                  8256      
_________________________________________________________________
dense_31 (Dense)             multiple                  2080      
_________________________________________________________________
dense_32 (Dense)             multiple                  330       
Total params: 244,522
Trainable params: 244,522
Non-trainable params: 0
_________________________________________________________________
0 loss: 2.3416376
78 Evaluate Acc: 0.1076 0.1076
100 loss: 0.54802066
200

Keras 风格的训练，验证过程

In [408]:
import tensorflow as tf
from tensorflow.keras import datasets, layers, optimizers, Sequential,  metrics

def preprocess(x, y):
    """
    x is a simple image, not a batch
    """
    x = tf.cast(x, dtype=tf.float32) / 255.
    x = tf.reshape(x, [28*28])
    y = tf.cast(y, dtype=tf.int32)
    y = tf.one_hot(y, depth=10)
    return x,y


batchsz = 128
(x, y), (x_val, y_val) = datasets.mnist.load_data()
print('datasets:', x.shape, y.shape, x.min(), x.max())



db = tf.data.Dataset.from_tensor_slices((x,y))
db = db.map(preprocess).shuffle(60000).batch(batchsz)
ds_val = tf.data.Dataset.from_tensor_slices((x_val, y_val))
ds_val = ds_val.map(preprocess).batch(batchsz) 

sample = next(iter(db))
print(sample[0].shape, sample[1].shape)

network = Sequential([
    layers.Dense(256, activation='relu'),
    layers.Dense(128, activation='relu'),
    layers.Dense(64, activation='relu'),
    layers.Dense(32, activation='relu'),
    layers.Dense(10)])

network.build(input_shape=(None, 28*28))
network.summary()

# compile
network.compile(optimizer=optimizers.Adam(learning_rate=0.01),
                loss=tf.losses.CategoricalCrossentropy(from_logits=True),
               metrics=['acc'])

# train
# network.fit包含了network.bulid的功能，参数初始化
network.fit(db, epochs=5, validation_data=ds_val, validation_freq=2)


datasets: (60000, 28, 28) (60000,) 0 255
(128, 784) (128, 10)
Model: "sequential_19"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_98 (Dense)             multiple                  200960    
_________________________________________________________________
dense_99 (Dense)             multiple                  32896     
_________________________________________________________________
dense_100 (Dense)            multiple                  8256      
_________________________________________________________________
dense_101 (Dense)            multiple                  2080      
_________________________________________________________________
dense_102 (Dense)            multiple                  330       
Total params: 244,522
Trainable params: 244,522
Non-trainable params: 0
_________________________________________________________________
Epoch 1/5
469/469 [==============================] 

自定义层

In [403]:
class MyDense(layers.Layer):
    def __init__(self, inp_dim, outp_dim):
        super(MyDense, self).__init__()
        
        self.kernel = self.add_variable('w', [inp_dim, outp_dim])
        self.bias = self.add_variable('b', [outp_dim])
        
    def call(self, inputs , training=None):
        out = inputs @ self.kernel + self.bias
        return out

#mylayer = MyDense(4,3)
#inputs = tf.ones([2,4])
#out = mylayer(inputs)
#out

class Mymodel(keras.Model):
    def __init__(self):
        super(Mymodel, self).__init__()
        self.fc1 = MyDense(28*28, 256)
        self.fc2 = MyDense(256,128)
        self.fc3 = MyDense(128,64)
        self.fc4 = MyDense(64,32)
        self.fc5 = MyDense(32,10)
        
    def call(self, inputs, training=None):
            x = self.fc1(inputs)
            x = tf.nn.relu(x)
            x = self.fc2(x)
            x = tf.nn.relu(x)
            x = self.fc3(x)
            x = tf.nn.relu(x)
            x = self.fc4(x)
            x = tf.nn.relu(x)
            x = self.fc5(x) 

            return x

network = Mymodel()  
network.compile(optimizer=optimizers.Adam(lr=0.01),
        loss=tf.losses.CategoricalCrossentropy(from_logits=True),
        metrics=['accuracy'])

network.build(input_shape=(4, 784))
network.summary()

Model: "mymodel_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
my_dense_36 (MyDense)        multiple                  200960    
_________________________________________________________________
my_dense_37 (MyDense)        multiple                  32896     
_________________________________________________________________
my_dense_38 (MyDense)        multiple                  8256      
_________________________________________________________________
my_dense_39 (MyDense)        multiple                  2080      
_________________________________________________________________
my_dense_40 (MyDense)        multiple                  330       
Total params: 244,522
Trainable params: 244,522
Non-trainable params: 0
_________________________________________________________________


In [410]:
import  tensorflow as tf
from    tensorflow.keras import datasets, layers, optimizers, Sequential, metrics
from 	tensorflow import keras

def preprocess(x, y):
    """
    x is a simple image, not a batch
    """
    x = tf.cast(x, dtype=tf.float32) / 255.
    x = tf.reshape(x, [28*28])
    y = tf.cast(y, dtype=tf.int32)
    y = tf.one_hot(y, depth=10)
    return x,y


batchsz = 128
(x, y), (x_val, y_val) = datasets.mnist.load_data()
print('datasets:', x.shape, y.shape, x.min(), x.max())



db = tf.data.Dataset.from_tensor_slices((x,y))
db = db.map(preprocess).shuffle(60000).batch(batchsz)
ds_val = tf.data.Dataset.from_tensor_slices((x_val, y_val))
ds_val = ds_val.map(preprocess).batch(batchsz) 

sample = next(iter(db))
print(sample[0].shape, sample[1].shape)


network = Sequential([layers.Dense(256, activation='relu'),
                     layers.Dense(128, activation='relu'),
                     layers.Dense(64, activation='relu'),
                     layers.Dense(32, activation='relu'),
                     layers.Dense(10)])
network.build(input_shape=(None, 28*28))
network.summary()


class MyDense(layers.Layer):

	def __init__(self, inp_dim, outp_dim):
		super(MyDense, self).__init__()

		self.kernel = self.add_variable('w', [inp_dim, outp_dim])
		self.bias = self.add_variable('b', [outp_dim])

	def call(self, inputs, training=None):

		out = inputs @ self.kernel + self.bias

		return out 

class MyModel(keras.Model):

	def __init__(self):
		super(MyModel, self).__init__()

		self.fc1 = MyDense(28*28, 256)
		self.fc2 = MyDense(256, 128)
		self.fc3 = MyDense(128, 64)
		self.fc4 = MyDense(64, 32)
		self.fc5 = MyDense(32, 10)

	def call(self, inputs, training=None):

		x = self.fc1(inputs)
		x = tf.nn.relu(x)
		x = self.fc2(x)
		x = tf.nn.relu(x)
		x = self.fc3(x)
		x = tf.nn.relu(x)
		x = self.fc4(x)
		x = tf.nn.relu(x)
		x = self.fc5(x) 

		return x


network = MyModel()


network.compile(optimizer=optimizers.Adam(lr=0.01),
		loss=tf.losses.CategoricalCrossentropy(from_logits=True),
		metrics=['accuracy']
	)

network.fit(db, epochs=5, validation_data=ds_val,
              validation_freq=2)
 
network.evaluate(ds_val)

sample = next(iter(ds_val))
x = sample[0]
y = sample[1] # one-hot
pred = network.predict(x) # [b, 10]
# convert back to number 
y = tf.argmax(y, axis=1)
pred = tf.argmax(pred, axis=1)

print(pred)
print(y)


datasets: (60000, 28, 28) (60000,) 0 255
(128, 784) (128, 10)
Model: "sequential_20"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_103 (Dense)            multiple                  200960    
_________________________________________________________________
dense_104 (Dense)            multiple                  32896     
_________________________________________________________________
dense_105 (Dense)            multiple                  8256      
_________________________________________________________________
dense_106 (Dense)            multiple                  2080      
_________________________________________________________________
dense_107 (Dense)            multiple                  330       
Total params: 244,522
Trainable params: 244,522
Non-trainable params: 0
_________________________________________________________________
Epoch 1/5
469/469 [==============================] 

In [2]:
import  tensorflow as tf
from tensorflow import keras
from    tensorflow.keras import layers, optimizers, datasets, Sequential
import  os

os.environ['TF_CPP_MIN_LOG_LEVEL']='2'
tf.random.set_seed(2345)

def preprocess(x, y):
    # [0~1]
    x = tf.cast(x, dtype=tf.float32) / 255.
    y = tf.cast(y, dtype=tf.int32)
    return x,y


(x,y), (x_test, y_test) = datasets.cifar100.load_data()
y = tf.squeeze(y, axis=1)
y_test = tf.squeeze(y_test, axis=1)
print(x.shape, y.shape, x_test.shape, y_test.shape)


train_db = tf.data.Dataset.from_tensor_slices((x,y))
train_db = train_db.shuffle(1000).map(preprocess).batch(128)

test_db = tf.data.Dataset.from_tensor_slices((x_test,y_test))
test_db = test_db.map(preprocess).batch(64)

sample = next(iter(train_db))
print('sample:', sample[0].shape, sample[1].shape,
      tf.reduce_min(sample[0]), tf.reduce_max(sample[0]))





(50000, 32, 32, 3) (50000,) (10000, 32, 32, 3) (10000,)
sample: (128, 32, 32, 3) (128,) tf.Tensor(0.0, shape=(), dtype=float32) tf.Tensor(1.0, shape=(), dtype=float32)


In [3]:
from tensorflow.keras import Model, Input

class Basenet(keras.Model):
    def __init__(self):
        super(Basenet, self).__init__()
        
        self.conv1 = layers.Conv2D(64,  kernel_size=[3, 3], padding="same", activation=tf.nn.relu)
        self.conv2 = layers.Conv2D(64,  kernel_size=[3, 3], padding="same", activation=tf.nn.relu)
        self.maxpool1 = layers.MaxPool2D(pool_size=[2, 2], strides=2, padding='same')
        
        self.conv3 = layers.Conv2D(128, kernel_size=[3, 3], padding="same", activation=tf.nn.relu)
        self.conv4 = layers.Conv2D(128, kernel_size=[3, 3], padding="same", activation=tf.nn.relu)
        self.maxpool2 = layers.MaxPool2D(pool_size=[2, 2], strides=2, padding='same')
        
        self.conv5 = layers.Conv2D(256, kernel_size=[3, 3], padding="same", activation=tf.nn.relu)
        self.conv6 = layers.Conv2D(256, kernel_size=[3, 3], padding="same", activation=tf.nn.relu)
        self.maxpool3 = layers.MaxPool2D(pool_size=[2, 2], strides=2, padding='same')
        
        self.conv7 = layers.Conv2D(512, kernel_size=[3, 3], padding="same", activation=tf.nn.relu)
        self.conv8 = layers.Conv2D(512, kernel_size=[3, 3], padding="same", activation=tf.nn.relu)
        self.maxpool4 = layers.MaxPool2D(pool_size=[2, 2], strides=2, padding='same')
        
        self.conv9 = layers.Conv2D(512, kernel_size=[3, 3], padding="same", activation=tf.nn.relu)
        self.conv10 = layers.Conv2D(512, kernel_size=[3, 3], padding="same", activation=tf.nn.relu)        
        self.maxpool5 = layers.MaxPool2D(pool_size=[2, 2], strides=2, padding='same')
    
    # forward
    def call(self, inputs, training=None):
        x = self.conv1(inputs)
        #print(x.shape)
        x = self.conv2(x)
        x = self.maxpool1(x)
        
        x = self.conv3(x)
        x = self.conv4(x)
        x = self.maxpool2(x)

        x = self.conv5(x)
        x = self.conv6(x)
        x = self.maxpool3(x)
        
        x = self.conv7(x)
        x = self.conv8(x)
        x = self.maxpool4(x)

        
        x = self.conv9(x)
        x = self.conv10(x)
        x = self.maxpool5(x)        
        
        return x

conv_network = Basenet()
conv_network.build(input_shape=(None,32,32,3))
conv_network.summary()


class fcNet(keras.Model):
    def __init__(self):
        super(fcNet, self).__init__()
        
        self.dense1 = layers.Dense(256, activation=tf.nn.relu)
        self.dense2 = layers.Dense(128, activation=tf.nn.relu)
        self.dense3 = layers.Dense(100)
    
    def call(self, inputs, training=None):
        x = self.dense1(inputs)
        x = self.dense2(x)
        x = self.dense3(x)
    
        return x
    
fc_network = fcNet()
fc_network.build(input_shape=(None, 512))
fc_network.summary()


# tf风格写法

optimizer = optimizers.Adam(learning_rate=1e-4)

variable = conv_network.trainable_variables + fc_network.trainable_variables

for epoch in range(2):
    for step, (x, y) in enumerate(train_db):
        with tf.GradientTape() as tape:
            out = conv_network(x)
            #print(out)
            out = tf.reshape(out, [-1, 512])
            logits = fc_network(out)
            
            y_onehot = tf.one_hot(y, depth=100)
            # compute loss
            loss = tf.losses.categorical_crossentropy(y_onehot, logits, from_logits=True)
            loss = tf.reduce_mean(loss)            
        grads = tape.gradient(loss, variable)
        optimizer.apply_gradients(zip(grads, variable))
        
        if step % 100 == 0:
            print(epoch, step, 'loss: ', float(loss))
            
    total_num = 0
    total_correct = 0
    for x,y in test_db:

        out = conv_network(x)
        out = tf.reshape(out, [-1, 512])
        logits = fc_network(out)
        prob = tf.nn.softmax(logits, axis=1)
        pred = tf.argmax(prob, axis=1)
        pred = tf.cast(pred, dtype=tf.int32)

        correct = tf.cast(tf.equal(pred, y), dtype=tf.int32)
        correct = tf.reduce_sum(correct)

        total_num += x.shape[0]
        total_correct += int(correct)

    acc = total_correct / total_num
    print(epoch, 'acc:', acc)            
  

Model: "basenet"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              multiple                  1792      
_________________________________________________________________
conv2d_1 (Conv2D)            multiple                  36928     
_________________________________________________________________
max_pooling2d (MaxPooling2D) multiple                  0         
_________________________________________________________________
conv2d_2 (Conv2D)            multiple                  73856     
_________________________________________________________________
conv2d_3 (Conv2D)            multiple                  147584    
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 multiple                  0         
_________________________________________________________________
conv2d_4 (Conv2D)            multiple                  2951